#!/bin/sh

COLOR_FG_BLACK="\[\e[01;30m\]"
COLOR_FG_RED="\[\e[01;31m\]"
COLOR_FG_GREEN="\[\e[01;32m\]"
COLOR_FG_YELLOW="\[\e[01;33m\]"
COLOR_FG_BLUE="\[\e[01;34m\]"
COLOR_FG_MAGENTA="\[\e[01;35m\]"
COLOR_FG_CYAN="\[\e[01;36m\]"
COLOR_FG_WHITE="\[\e[01;37m\]"
COLOR_FG_BRIGHT_BLACK="\[\e[01;90m\]"
COLOR_FG_BRIGHT_RED="\[\e[01;91m\]"
COLOR_FG_BRIGHT_GREEN="\[\e[01;92m\]"
COLOR_FG_BRIGHT_YELLOW="\[\e[01;93m\]"
COLOR_FG_BRIGHT_BLUE="\[\e[01;94m\]"
COLOR_FG_BRIGHT_MAGENTA="\[\e[01;95m\]"
COLOR_FG_BRIGHT_CYAN="\[\e[01;96m\]"
COLOR_FG_BRIGHT_WHITE="\[\e[01;97m\]"
COLOR_FG_DEFAULT="\[\e[00m\]"

# Debian style
export PS1="${COLOR_FG_GREEN}\u@\h${COLOR_FG_BLUE} \w \$${COLOR_FG_DEFAULT} "

# Debian style (root)
export PS1="${COLOR_FG_RED}\h${COLOR_FG_BLUE} \w \$${COLOR_FG_DEFAULT} "